#!/bin/bash
#!/bin/bash
if [ "$#" -ne 2 ]; then
    echo "You must enter exactly 2 command line arguments"
else
	$fext = `$1`
	$fsize = `$2`

	for f in *.$fext
	do
		name=`echo "$f" | sed -e "s/.JPG$//g"`
		convert "$f" -resize $fsize "$name.jpg"
	done
	rm *.$fext
fi