#!/bin/bash
if [ "$#" -lt 2 ]; then
    echo "You must enter exactly 2 command line arguments"
else
	fext=`echo "$1"`
	fsize=`echo "$2"`

	for f in *.$fext
	do
		name=`echo "$f" | sed -e "s/.JPG$//g"`
		case "$#" in
		2)	convert "$f" -resize $fsize "$name.jpg";;
		3)	convert "$f" -resize $fsize "$name.jpg" -quality "$3";;
		esac
	done
	rm *.$fext
fi
